# seed.py
from app import app, db
from models import Nursery


nursery_data = [

    # ========================
    # ألمانيا – Germany
    # ========================

    {
        "name": "Bright Horizons Academy",
        "location": "Berlin, Germany",
        "rating": 4.9,
        "reviews_count": 234,
        "curriculum": "Montessori,International",
        "features": "Outdoor Garden,Art Studio,Music Classes,Swimming Pool",
        "price": 850,
        "currency": "EUR",
        "phone": "+49 30 12345678",
        "capacity": 60,
        "age_groups": "6 months - 6 years",
        "total_children": 58,
        "staff_ratio": "1:4",
        "parent_satisfaction": 96,
        "teacher_quality": 94,
        "facilities_rating": 98,
        "safety_rating": 99,
        "description": "A premium nursery offering world-class Montessori education with state-of-the-art facilities.",
        "google_maps_url": "https://maps.google.com/?q=Berlin+Germany"
    },
    {
        "name": "Little Explorers",
        "location": "Munich, Germany",
        "rating": 4.8,
        "reviews_count": 189,
        "curriculum": "British,Montessori",
        "features": "Science Lab,Library,Sports Field,Healthy Meals",
        "price": 780,
        "currency": "EUR",
        "phone": "+49 89 98765432",
        "capacity": 75,
        "age_groups": "1 - 6 years",
        "total_children": 72,
        "staff_ratio": "1:5",
        "parent_satisfaction": 93,
        "teacher_quality": 91,
        "facilities_rating": 95,
        "safety_rating": 97,
        "description": "Encouraging curiosity and exploration through hands-on learning experiences.",
        "google_maps_url": "https://maps.google.com/?q=Munich+Germany"
    },
    {
        "name": "Rainbow Kids Center",
        "location": "Hamburg, Germany",
        "rating": 4.7,
        "reviews_count": 156,
        "curriculum": "American,International",
        "features": "Bilingual Program,Technology Lab,Dance Studio,Organic Food",
        "price": 920,
        "currency": "EUR",
        "phone": "+49 40 55566677",
        "capacity": 50,
        "age_groups": "6 months - 5 years",
        "total_children": 48,
        "staff_ratio": "1:3",
        "parent_satisfaction": 95,
        "teacher_quality": 96,
        "facilities_rating": 93,
        "safety_rating": 98,
        "description": "A vibrant learning environment with focus on bilingual education and creativity.",
        "google_maps_url": "https://maps.google.com/?q=Hamburg+Germany"
    },
    {
        "name": "Sunshine Nursery",
        "location": "Frankfurt, Germany",
        "rating": 4.6,
        "reviews_count": 142,
        "curriculum": "Montessori",
        "features": "Nature Walks,Yoga Classes,Art Therapy,Parent Workshops",
        "price": 720,
        "currency": "EUR",
        "phone": "+49 69 33344455",
        "capacity": 45,
        "age_groups": "1 - 6 years",
        "total_children": 43,
        "staff_ratio": "1:5",
        "parent_satisfaction": 91,
        "teacher_quality": 89,
        "facilities_rating": 90,
        "safety_rating": 95,
        "description": "Nurturing young minds through nature-based Montessori education.",
        "google_maps_url": "https://maps.google.com/?q=Frankfurt+Germany"
    },
    {
        "name": "Future Leaders Academy",
        "location": "Cologne, Germany",
        "rating": 4.9,
        "reviews_count": 201,
        "curriculum": "International,British",
        "features": "STEM Program,Robotics,Language Lab,Indoor Playground",
        "price": 950,
        "currency": "EUR",
        "phone": "+49 221 77788899",
        "capacity": 80,
        "age_groups": "6 months - 6 years",
        "total_children": 78,
        "staff_ratio": "1:4",
        "parent_satisfaction": 97,
        "teacher_quality": 98,
        "facilities_rating": 99,
        "safety_rating": 99,
        "description": "Preparing tomorrow's leaders with cutting-edge education and technology.",
        "google_maps_url": "https://maps.google.com/?q=Cologne+Germany"
    },
    {
        "name": "Happy Hearts Nursery",
        "location": "Stuttgart, Germany",
        "rating": 4.5,
        "reviews_count": 128,
        "curriculum": "Montessori,American",
        "features": "Music Therapy,Sensory Room,Cooking Classes,Pet Therapy",
        "price": 690,
        "currency": "EUR",
        "phone": "+49 711 22233344",
        "capacity": 55,
        "age_groups": "1 - 5 years",
        "total_children": 52,
        "staff_ratio": "1:5",
        "parent_satisfaction": 90,
        "teacher_quality": 88,
        "facilities_rating": 87,
        "safety_rating": 94,
        "description": "Creating happy memories through play-based learning and emotional development.",
        "google_maps_url": "https://maps.google.com/?q=Stuttgart+Germany"
    },
    {
        "name": "Discovery Kids",
        "location": "Düsseldorf, Germany",
        "rating": 4.8,
        "reviews_count": 176,
        "curriculum": "British,International",
        "features": "Forest School,Drama Classes,Chess Club,Nutrition Program",
        "price": 880,
        "currency": "EUR",
        "phone": "+49 211 66677788",
        "capacity": 70,
        "age_groups": "6 months - 6 years",
        "total_children": 68,
        "staff_ratio": "1:4",
        "parent_satisfaction": 94,
        "teacher_quality": 93,
        "facilities_rating": 96,
        "safety_rating": 98,
        "description": "Inspiring young minds through discovery-based learning and outdoor education.",
        "google_maps_url": "https://maps.google.com/?q=Dusseldorf+Germany"
    },
    {
        "name": "Little Einsteins",
        "location": "Leipzig, Germany",
        "rating": 4.7,
        "reviews_count": 163,
        "curriculum": "American,Montessori",
        "features": "Science Experiments,Math Games,Reading Corner,Creative Arts",
        "price": 750,
        "currency": "EUR",
        "phone": "+49 341 44455566",
        "capacity": 65,
        "age_groups": "1 - 6 years",
        "total_children": 62,
        "staff_ratio": "1:5",
        "parent_satisfaction": 92,
        "teacher_quality": 90,
        "facilities_rating": 91,
        "safety_rating": 96,
        "description": "Fostering genius through early STEM education and creative thinking.",
        "google_maps_url": "https://maps.google.com/?q=Leipzig+Germany"
    },
    {
        "name": "Tiny Treasures",
        "location": "Dresden, Germany",
        "rating": 4.6,
        "reviews_count": 134,
        "curriculum": "Montessori",
        "features": "Baby Massage,Sensory Play,Parent-Child Classes,Sleep Training",
        "price": 680,
        "currency": "EUR",
        "phone": "+49 351 88899900",
        "capacity": 40,
        "age_groups": "3 months - 3 years",
        "total_children": 38,
        "staff_ratio": "1:3",
        "parent_satisfaction": 93,
        "teacher_quality": 91,
        "facilities_rating": 89,
        "safety_rating": 97,
        "description": "Specialized care for infants and toddlers with gentle Montessori approach.",
        "google_maps_url": "https://maps.google.com/?q=Dresden+Germany"
    },
    {
        "name": "Global Kids Academy",
        "location": "Hannover, Germany",
        "rating": 4.8,
        "reviews_count": 198,
        "curriculum": "International,British",
        "features": "Multilingual Staff,Cultural Events,World Cuisine,Exchange Programs",
        "price": 820,
        "currency": "EUR",
        "phone": "+49 511 11122233",
        "capacity": 85,
        "age_groups": "1 - 6 years",
        "total_children": 82,
        "staff_ratio": "1:4",
        "parent_satisfaction": 95,
        "teacher_quality": 94,
        "facilities_rating": 94,
        "safety_rating": 98,
        "description": "Celebrating diversity and preparing global citizens through multicultural education.",
        "google_maps_url": "https://maps.google.com/?q=Hannover+Germany"
    },
    {
        "name": "Nature's Nest",
        "location": "Nuremberg, Germany",
        "rating": 4.7,
        "reviews_count": 145,
        "curriculum": "Montessori,International",
        "features": "Eco-Friendly,Garden Program,Animal Care,Sustainability Education",
        "price": 770,
        "currency": "EUR",
        "phone": "+49 911 55566677",
        "capacity": 50,
        "age_groups": "1 - 6 years",
        "total_children": 47,
        "staff_ratio": "1:5",
        "parent_satisfaction": 94,
        "teacher_quality": 92,
        "facilities_rating": 93,
        "safety_rating": 96,
        "description": "Teaching environmental responsibility through nature-immersive education.",
        "google_maps_url": "https://maps.google.com/?q=Nuremberg+Germany"
    },
    {
        "name": "Creative Minds Studio",
        "location": "Bremen, Germany",
        "rating": 4.9,
        "reviews_count": 187,
        "curriculum": "American,International",
        "features": "Art Gallery,Theater,Photography,Design Thinking",
        "price": 890,
        "currency": "EUR",
        "phone": "+49 421 99988877",
        "capacity": 60,
        "age_groups": "2 - 6 years",
        "total_children": 58,
        "staff_ratio": "1:4",
        "parent_satisfaction": 96,
        "teacher_quality": 97,
        "facilities_rating": 98,
        "safety_rating": 99,
        "description": "Unleashing creativity and innovation through arts-integrated education.",
        "google_maps_url": "https://maps.google.com/?q=Bremen+Germany"
    },

    # ========================
    # برلين – Berlin
    # ========================

    {
        "name": "Berlin International Kids",
        "location": "Mitte, Berlin, Germany",
        "rating": 4.9,
        "reviews_count": 312,
        "curriculum": "International,British",
        "features": "Rooftop Garden,Language Lab,Tech Hub,Cultural Exchange",
        "price": 980,
        "currency": "EUR",
        "phone": "+49 30 88899900",
        "capacity": 90,
        "age_groups": "6 months - 6 years",
        "total_children": 87,
        "staff_ratio": "1:3",
        "parent_satisfaction": 98,
        "teacher_quality": 97,
        "facilities_rating": 99,
        "safety_rating": 99,
        "description": "Berlin's premier international nursery in the heart of the city, offering world-class multilingual education.",
        "google_maps_url": "https://maps.google.com/?q=Mitte+Berlin+Germany"
    },
    {
        "name": "Prenzlauer Berg Academy",
        "location": "Prenzlauer Berg, Berlin, Germany",
        "rating": 4.8,
        "reviews_count": 267,
        "curriculum": "Montessori,International",
        "features": "Urban Farm,Maker Space,Yoga Studio,Organic Kitchen",
        "price": 920,
        "currency": "EUR",
        "phone": "+49 30 77766655",
        "capacity": 70,
        "age_groups": "1 - 6 years",
        "total_children": 68,
        "staff_ratio": "1:4",
        "parent_satisfaction": 96,
        "teacher_quality": 95,
        "facilities_rating": 97,
        "safety_rating": 98,
        "description": "A progressive nursery combining Montessori principles with urban sustainability education.",
        "google_maps_url": "https://maps.google.com/?q=Prenzlauer+Berg+Berlin+Germany"
    },
    {
        "name": "Charlottenburg Stars",
        "location": "Charlottenburg, Berlin, Germany",
        "rating": 4.7,
        "reviews_count": 198,
        "curriculum": "British,American",
        "features": "Music Academy,Sports Complex,Science Lab,Art Atelier",
        "price": 860,
        "currency": "EUR",
        "phone": "+49 30 55544433",
        "capacity": 65,
        "age_groups": "1 - 6 years",
        "total_children": 62,
        "staff_ratio": "1:4",
        "parent_satisfaction": 94,
        "teacher_quality": 93,
        "facilities_rating": 96,
        "safety_rating": 97,
        "description": "Nurturing future stars through comprehensive arts, sports, and academic programs.",
        "google_maps_url": "https://maps.google.com/?q=Charlottenburg+Berlin+Germany"
    },
    {
        "name": "Kreuzberg Creative Hub",
        "location": "Kreuzberg, Berlin, Germany",
        "rating": 4.8,
        "reviews_count": 223,
        "curriculum": "International,Montessori",
        "features": "Street Art Studio,Community Garden,Multicultural Kitchen,Dance Floor",
        "price": 840,
        "currency": "EUR",
        "phone": "+49 30 66677788",
        "capacity": 55,
        "age_groups": "1 - 6 years",
        "total_children": 53,
        "staff_ratio": "1:4",
        "parent_satisfaction": 95,
        "teacher_quality": 94,
        "facilities_rating": 94,
        "safety_rating": 96,
        "description": "A vibrant, diverse nursery celebrating creativity and cultural diversity in Berlin's artistic heart.",
        "google_maps_url": "https://maps.google.com/?q=Kreuzberg+Berlin+Germany"
    },

    # ========================
    # لندن – London, UK
    # ========================

    {
        "name": "Kensington Royal Academy",
        "location": "Kensington, London, UK",
        "rating": 4.9,
        "reviews_count": 345,
        "curriculum": "British,International",
        "features": "Royal Gardens,Classical Music,Etiquette Classes,French Lessons",
        "price": 1150,
        "currency": "EUR",
        "phone": "+44 20 7123 4567",
        "capacity": 80,
        "age_groups": "6 months - 5 years",
        "total_children": 78,
        "staff_ratio": "1:3",
        "parent_satisfaction": 98,
        "teacher_quality": 98,
        "facilities_rating": 99,
        "safety_rating": 99,
        "description": "London's most prestigious nursery offering traditional British education with royal standards.",
        "google_maps_url": "https://maps.google.com/?q=Kensington+London+UK"
    },
    {
        "name": "Camden Creative Kids",
        "location": "Camden, London, UK",
        "rating": 4.7,
        "reviews_count": 289,
        "curriculum": "International,American",
        "features": "Music Studio,Theater Stage,Art Gallery,Innovation Lab",
        "price": 950,
        "currency": "EUR",
        "phone": "+44 20 7234 5678",
        "capacity": 70,
        "age_groups": "1 - 6 years",
        "total_children": 67,
        "staff_ratio": "1:4",
        "parent_satisfaction": 94,
        "teacher_quality": 95,
        "facilities_rating": 96,
        "safety_rating": 97,
        "description": "A creative haven in Camden where children explore arts, music, and innovation.",
        "google_maps_url": "https://maps.google.com/?q=Camden+London+UK"
    },
    {
        "name": "Chelsea Garden Nursery",
        "location": "Chelsea, London, UK",
        "rating": 4.8,
        "reviews_count": 312,
        "curriculum": "Montessori,British",
        "features": "Botanical Garden,Greenhouse,Nature Trails,Organic Farm",
        "price": 1080,
        "currency": "EUR",
        "phone": "+44 20 7345 6789",
        "capacity": 60,
        "age_groups": "6 months - 6 years",
        "total_children": 58,
        "staff_ratio": "1:3",
        "parent_satisfaction": 97,
        "teacher_quality": 96,
        "facilities_rating": 98,
        "safety_rating": 99,
        "description": "An enchanting garden-based nursery where children connect with nature in the heart of Chelsea.",
        "google_maps_url": "https://maps.google.com/?q=Chelsea+London+UK"
    },
    {
        "name": "Notting Hill International",
        "location": "Notting Hill, London, UK",
        "rating": 4.9,
        "reviews_count": 298,
        "curriculum": "International,British",
        "features": "World Cultures Room,Language Center,Global Kitchen,Travel Library",
        "price": 1020,
        "currency": "EUR",
        "phone": "+44 20 7456 7890",
        "capacity": 75,
        "age_groups": "1 - 6 years",
        "total_children": 73,
        "staff_ratio": "1:4",
        "parent_satisfaction": 96,
        "teacher_quality": 97,
        "facilities_rating": 97,
        "safety_rating": 98,
        "description": "Celebrating global diversity and preparing world citizens in vibrant Notting Hill.",
        "google_maps_url": "https://maps.google.com/?q=Notting+Hill+London+UK"
    },
    {
        "name": "Shoreditch Tech Tots",
        "location": "Shoreditch, London, UK",
        "rating": 4.7,
        "reviews_count": 234,
        "curriculum": "American,International",
        "features": "Coding Classes,Robotics Lab,3D Printing,Digital Art Studio",
        "price": 990,
        "currency": "EUR",
        "phone": "+44 20 7567 8901",
        "capacity": 65,
        "age_groups": "2 - 6 years",
        "total_children": 62,
        "staff_ratio": "1:4",
        "parent_satisfaction": 93,
        "teacher_quality": 94,
        "facilities_rating": 98,
        "safety_rating": 96,
        "description": "London's most innovative tech-focused nursery preparing children for the digital future.",
        "google_maps_url": "https://maps.google.com/?q=Shoreditch+London+UK"
    },

    # ========================
    # الإمارات – UAE
    # ========================

    {
        "name": "Little Steps Nursery",
        "location": "Dubai, UAE",
        "rating": 4.8,
        "reviews_count": 310,
        "curriculum": "British,Montessori",
        "features": "Outdoor Play Area,Water Play,Reading Corner,STEM Lab",
        "price": 2500,
        "currency": "AED",
        "phone": "+971 4 2233445",
        "capacity": 70,
        "age_groups": "6 months - 5 years",
        "total_children": 68,
        "staff_ratio": "1:4",
        "parent_satisfaction": 95,
        "teacher_quality": 94,
        "facilities_rating": 96,
        "safety_rating": 97,
        "description": "A warm, inclusive nursery offering world-class British early education.",
        "google_maps_url": "https://maps.google.com/?q=Dubai+UAE"
    },
    {
        "name": "Happy Minds Nursery",
        "location": "Abu Dhabi, UAE",
        "rating": 4.9,
        "reviews_count": 280,
        "curriculum": "American,International",
        "features": "Music Room,Art Room,STEM Lab,Healthy Meals",
        "price": 2700,
        "currency": "AED",
        "phone": "+971 2 9988776",
        "capacity": 80,
        "age_groups": "6 months - 6 years",
        "total_children": 76,
        "staff_ratio": "1:3",
        "parent_satisfaction": 97,
        "teacher_quality": 96,
        "facilities_rating": 95,
        "safety_rating": 98,
        "description": "Nurturing confident learners with hands-on American curriculum.",
        "google_maps_url": "https://maps.google.com/?q=Abu+Dhabi+UAE"
    }
]


if __name__ == "__main__":
    with app.app_context():
        db.drop_all()
        db.create_all()

        for data in nursery_data:
            nursery = Nursery(**data)
            db.session.add(nursery)

        db.session.commit()
        print("✅ Database seeded successfully with all nurseries.")
